package Principal;

import java.util.ArrayList;

import javax.swing.*;

import Interfaz.*;
import Logica.*;

public class Inicializadora{
	public static void main(String[] args) {

		SwingUtilities.invokeLater(new Runnable() {
			@SuppressWarnings("serial")
			public void run() {

				Vicedecanato vicedecanato = new Vicedecanato();

				Departamento depto1 = new Departamento("Departamento de Ciencias Computacionales");
				Departamento depto2 = new Departamento("Departamento de Ingeniería Eléctrica");
				Departamento depto3 = new Departamento("Departamento de Matemáticas Aplicadas");

				vicedecanato.agregarDepartamento(depto1);
				vicedecanato.agregarDepartamento(depto2);
				vicedecanato.agregarDepartamento(depto3);

				//Aqui se crean 60 docentes y se agregan al vicedecanato
				Docente d1 = new Docente("Carlos", "Pérez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d2 = new Docente("María", "Gómez", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d3 = new Docente("Luis", "Martínez", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d4 = new Docente("Ana", "López", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d5 = new Docente("Javier", "Rodríguez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d6 = new Docente("Lucía", "Fernández", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d7 = new Docente("Diego", "Sánchez", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d8 = new Docente("Andrea", "Ruiz", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d9 = new Docente("Miguel", "Hernández", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d10 = new Docente("Laura", "Díaz", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d11 = new Docente("David", "Torres", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d12 = new Docente("Valentina", "Ramírez", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d13 = new Docente("Santiago", "Flores", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d14 = new Docente("Camila", "Morales", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d15 = new Docente("Daniel", "Castro", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d16 = new Docente("Natalia", "Vargas", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d17 = new Docente("Alejandro", "Ortega", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d18 = new Docente("Isabella", "Rojas", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d19 = new Docente("Mateo", "Silva", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d20 = new Docente("Daniela", "Romero", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d21 = new Docente("José", "Jiménez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d22 = new Docente("Carolina", "Mendoza", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d23 = new Docente("Sebastián", "Cortés", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d24 = new Docente("Paula", "Guerrero", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d25 = new Docente("Fernando", "Reyes", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d26 = new Docente("Valeria", "Chávez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d27 = new Docente("Cristian", "Navarro", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d28 = new Docente("Emily", "Medina", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d29 = new Docente("Jhon", "Cárdenas", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d30 = new Docente("Sofía", "Ramos", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d31 = new Docente("Andrés", "Molina", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d32 = new Docente("Paola", "Ávila", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d33 = new Docente("Kevin", "Peña", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d34 = new Docente("Gabriela", "Salazar", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d35 = new Docente("Oscar", "León", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d36 = new Docente("Elena", "Vega", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d37 = new Docente("Manuel", "Ibarra", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d38 = new Docente("Renata", "Zambrano", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d39 = new Docente("Emilio", "Benítez", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d40 = new Docente("Claudia", "Velasco", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d41 = new Docente("Enrique", "Rangel", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d42 = new Docente("Tatiana", "Quintero", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d43 = new Docente("Julio", "Cevallos", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d44 = new Docente("Adriana", "Cedeño", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d45 = new Docente("Ricardo", "Paredes", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d46 = new Docente("Verónica", "Duarte", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d47 = new Docente("Guillermo", "Escobar", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d48 = new Docente("Melissa", "Bustos", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d49 = new Docente("Francisco", "Palacios", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d50 = new Docente("Patricia", "Arroyo", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d51 = new Docente("Hugo", "Maldonado", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d52 = new Docente("Karen", "Carrasco", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d53 = new Docente("Mario", "Bravo", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d54 = new Docente("Yessica", "Vargas", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d55 = new Docente("Alberto", "Montoya", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d56 = new Docente("Jessica", "Suárez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d57 = new Docente("Alex", "Correa", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d58 = new Docente("Liliana", "Ponce", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d59 = new Docente("Raúl", "Alarcón", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d60 = new Docente("Vanessa", "Mejía", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d61 = new Docente("Amadeo", "Villalba Montes", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d62 = new Docente("Belisario", "Narváez Roldán", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d63 = new Docente("Casimira", "Del Valle Ponce", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d64 = new Docente("Dacio", "Zambrano Alarcón", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d65 = new Docente("Eulalia", "Barros Quintana", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d66 = new Docente("Fructuoso", "Mesa Córdoba", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d67 = new Docente("Griselda", "Pizarro Valverde", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d68 = new Docente("Hermógenes", "Lagos Espinosa", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d69 = new Docente("Ifigenia", "Maldonado Rivas", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d70 = new Docente("Jovito", "Carrasco Lago", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d71 = new Docente("Kilian", "Roldán Páez", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d72 = new Docente("Lucrecia", "Sarmiento Montes", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d73 = new Docente("Mamerto", "Vega Otero", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d74 = new Docente("Nemesio", "Galindo Valle", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d75 = new Docente("Otilia", "Castañeda Ríos", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d76 = new Docente("Pánfilo", "Miranda Lago", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d77 = new Docente("Querubín", "Aguirre Pino", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d78 = new Docente("Régulo", "Solano Roldán", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d79 = new Docente("Serafina", "Montenegro Páez", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d80 = new Docente("Tadeo", "Cervantes Espinoza", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d81 = new Docente("Úrsula", "Ojeda Valdivia", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d82 = new Docente("Verenice", "Lara Montesinos", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d83 = new Docente("Wálter", "Méndez Ríos", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d84 = new Docente("Ximena", "Cortés Ocampo", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d85 = new Docente("Yolando", "Peralta Villalba", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d86 = new Docente("Zenaida", "Ríos Zambrano", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d87 = new Docente("Anacleto", "Montes Pizarro", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d88 = new Docente("Brígida", "Alarcón Narváez", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d89 = new Docente("Cándido", "Quintana Barros", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d90 = new Docente("Dorotea", "Córdoba Mesa", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d91 = new Docente("Eleuterio", "Valverde Lagos", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d92 = new Docente("Fidelia", "Espinosa Maldonado", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d93 = new Docente("Gervasio", "Rivas Carrasco", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d94 = new Docente("Hilario", "Lago Roldán", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d95 = new Docente("Isidora", "Páez Sarmiento", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d96 = new Docente("Jacinto", "Montes Vega", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d97 = new Docente("Leocadia", "Valle Galindo", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d98 = new Docente("Macario", "Ríos Castañeda", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d99 = new Docente("Natalicio", "Lago Miranda", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d100 = new Docente("Olegario", "Pino Aguirre", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d101 = new Docente("Pacífica", "Roldán Solano", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d102 = new Docente("Quirino", "Páez Montenegro", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d103 = new Docente("Rosalía", "Espinoza Cervantes", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d104 = new Docente("Saturnino", "Valdivia Ojeda", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d105 = new Docente("Teodosia", "Montesinos Lara", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d106 = new Docente("Ulpiano", "Ríos Méndez", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d107 = new Docente("Venancia", "Ocampo Cortés", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d108 = new Docente("Wenceslao", "Villalba Peralta", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d109 = new Docente("Xenia", "Zambrano Ríos", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d110 = new Docente("Yago", "Pizarro Montes", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d111 = new Docente("Zoraida", "Narváez Alarcón", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d112 = new Docente("Adelio", "Barros Quintana", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d113 = new Docente("Berta", "Mesa Córdoba", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d114 = new Docente("Celso", "Valverde Pizarro", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d115 = new Docente("Dina", "Lagos Espinosa", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d116 = new Docente("Eligio", "Maldonado Rivas", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d117 = new Docente("Fabiola", "Carrasco Lago", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d118 = new Docente("Galo", "Roldán Páez", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d119 = new Docente("Herminia", "Sarmiento Montes", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d120 = new Docente("Inocencio", "Vega Otero", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d121 = new Docente("Jovita", "Galindo Valle", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d122 = new Docente("Lauro", "Castañeda Ríos", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d123 = new Docente("Melania", "Miranda Lago", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d124 = new Docente("Narciso", "Aguirre Pino", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d125 = new Docente("Otilio", "Solano Roldán", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d126 = new Docente("Palmira", "Montenegro Páez", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d127 = new Docente("Quintín", "Cervantes Espinoza", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d128 = new Docente("Rita", "Ojeda Valdivia", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d129 = new Docente("Silvano", "Lara Montesinos", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d130 = new Docente("Tarsila", "Méndez Ríos", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d131 = new Docente("Urbano", "Cortés Ocampo", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d132 = new Docente("Viviana", "Peralta Villalba", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d133 = new Docente("Wilfredo", "Ríos Zambrano", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d134 = new Docente("Ximena", "Montes Pizarro", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d135 = new Docente("Yolando", "Alarcón Narváez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d136 = new Docente("Zacarías", "Quintana Barros", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d137 = new Docente("Adelaida", "Córdoba Mesa", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d138 = new Docente("Baldomero", "Valverde Lagos", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d139 = new Docente("Cándida", "Espinosa Maldonado", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d140 = new Docente("Demetrio", "Rivas Carrasco", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d141 = new Docente("Esmeralda", "Lago Roldán", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d142 = new Docente("Fulgencio", "Páez Sarmiento", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d143 = new Docente("Gertrudis", "Montes Vega", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d144 = new Docente("Hilarión", "Valle Galindo", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d145 = new Docente("Ildefonso", "Ríos Castañeda", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d146 = new Docente("Jacinta", "Lago Miranda", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d147 = new Docente("Leandro", "Pino Aguirre", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d148 = new Docente("Marcelina", "Roldán Solano", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d149 = new Docente("Nicanor", "Páez Montenegro", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d150 = new Docente("Olimpia", "Espinoza Cervantes", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d151 = new Docente("Pancracio", "Valdivia Ojeda", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d152 = new Docente("Querubina", "Montesinos Lara", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d153 = new Docente("Ramiro", "Ríos Méndez", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d154 = new Docente("Salustiana", "Ocampo Cortés", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d155 = new Docente("Tiburcio", "Villalba Peralta", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d156 = new Docente("Ubaldo", "Zambrano Ríos", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d157 = new Docente("Valeria", "Pizarro Montes", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d158 = new Docente("Waldemar", "Narváez Alarcón", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d159 = new Docente("Xavier", "Barros Quintana", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d160 = new Docente("Yolanda", "Mesa Córdoba", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d161 = new Docente("Zósimo", "Valverde Pizarro", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d162 = new Docente("Amparo", "Lagos Espinosa", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d163 = new Docente("Bernabé", "Maldonado Rivas", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d164 = new Docente("Cleto", "Carrasco Lago", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d165 = new Docente("Dionisia", "Roldán Páez", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d166 = new Docente("Eusebio", "Sarmiento Montes", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d167 = new Docente("Fidencia", "Vega Otero", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d168 = new Docente("Gumersindo", "Galindo Valle", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d169 = new Docente("Honorina", "Castañeda Ríos", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d170 = new Docente("Inocencia", "Miranda Lago", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d171 = new Docente("Justino", "Aguirre Pino", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d172 = new Docente("Leticia", "Solano Roldán", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d173 = new Docente("Macario", "Montenegro Páez", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d174 = new Docente("Natalia", "Cervantes Espinoza", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d175 = new Docente("Ovidio", "Ojeda Valdivia", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d176 = new Docente("Priscila", "Lara Montesinos", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d177 = new Docente("Quirino", "Méndez Ríos", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d178 = new Docente("Rosendo", "Cortés Ocampo", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d179 = new Docente("Simeón", "Peralta Villalba", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d180 = new Docente("Teodora", "Ríos Zambrano", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d181 = new Docente("Ulises", "Montes Pizarro", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d182 = new Docente("Venancio", "Alarcón Narváez", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d183 = new Docente("Wenceslada", "Quintana Barros", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d184 = new Docente("Xenón", "Córdoba Mesa", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d185 = new Docente("Yolanda", "Valverde Lagos", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d186 = new Docente("Zenaido", "Espinosa Maldonado", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d187 = new Docente("Adolfo", "Rivas Carrasco", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d188 = new Docente("Benigna", "Lago Roldán", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d189 = new Docente("Celestino", "Páez Sarmiento", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d190 = new Docente("Doroteo", "Montes Vega", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d191 = new Docente("Eufemia", "Valle Galindo", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d192 = new Docente("Froilán", "Ríos Castañeda", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d193 = new Docente("Gervasia", "Lago Miranda", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d194 = new Docente("Higinio", "Pino Aguirre", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d195 = new Docente("Isaura", "Roldán Solano", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d196 = new Docente("Juliano", "Páez Montenegro", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d197 = new Docente("Leonila", "Espinoza Cervantes", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d198 = new Docente("Martín", "Valdivia Ojeda", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d199 = new Docente("Natalia", "Montesinos Lara", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d200 = new Docente("Otilio", "Ríos Méndez", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d201 = new Docente("Pascuala", "Ocampo Cortés", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d202 = new Docente("Quintiliano", "Villalba Peralta", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d203 = new Docente("Ruperta", "Zambrano Ríos", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d204 = new Docente("Secundino", "Pizarro Montes", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d205 = new Docente("Teófila", "Narváez Alarcón", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d206 = new Docente("Urbana", "Barros Quintana", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d207 = new Docente("Valentín", "Mesa Córdoba", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d208 = new Docente("Wilfreda", "Valverde Pizarro", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d209 = new Docente("Xavier", "Lagos Espinosa", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d210 = new Docente("Yolanda", "Maldonado Rivas", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d211 = new Docente("Zacarías", "Carrasco Lago", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d212 = new Docente("Adela", "Roldán Páez", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d213 = new Docente("Balduino", "Sarmiento Montes", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d214 = new Docente("Carmelita", "Vega Otero", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d215 = new Docente("Damián", "Galindo Valle", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d216 = new Docente("Eleuteria", "Castañeda Ríos", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d217 = new Docente("Fortunato", "Miranda Lago", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d218 = new Docente("Gertrudis", "Aguirre Pino", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d219 = new Docente("Hilario", "Solano Roldán", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d220 = new Docente("Inés", "Montenegro Páez", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d221 = new Docente("Jacobo", "Cervantes Espinoza", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d222 = new Docente("Leocadia", "Ojeda Valdivia", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d223 = new Docente("Marcial", "Lara Montesinos", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d224 = new Docente("Nemesio", "Méndez Ríos", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d225 = new Docente("Olegaria", "Cortés Ocampo", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d226 = new Docente("Pánfilo", "Peralta Villalba", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d227 = new Docente("Quiteria", "Ríos Zambrano", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d228 = new Docente("Raimundo", "Montes Pizarro", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d229 = new Docente("Salomé", "Alarcón Narváez", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d230 = new Docente("Tadeo", "Quintana Barros", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d231 = new Docente("Ubalda", "Córdoba Mesa", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d232 = new Docente("Vicenta", "Valverde Lagos", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d233 = new Docente("Waldino", "Espinosa Maldonado", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d234 = new Docente("Ximena", "Rivas Carrasco", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d235 = new Docente("Yago", "Lago Roldán", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d236 = new Docente("Zenaida", "Páez Sarmiento", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d237 = new Docente("Ambrocio", "Montes Vega", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d238 = new Docente("Bibiana", "Valle Galindo", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d239 = new Docente("Cipriano", "Ríos Castañeda", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d240 = new Docente("Dorila", "Lago Miranda", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d241 = new Docente("Eusebia", "Pino Aguirre", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d242 = new Docente("Fidel", "Roldán Solano", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d243 = new Docente("Gaudencia", "Páez Montenegro", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d244 = new Docente("Humberto", "Espinoza Cervantes", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d245 = new Docente("Ildefonsa", "Valdivia Ojeda", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d246 = new Docente("Jacinta", "Montesinos Lara", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d247 = new Docente("Leocadio", "Ríos Méndez", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d248 = new Docente("Marcela", "Ocampo Cortés", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d249 = new Docente("Narcisa", "Villalba Peralta", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d250 = new Docente("Otilia", "Zambrano Ríos", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d251 = new Docente("Pío", "Pizarro Montes", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d252 = new Docente("Querubina", "Narváez Alarcón", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d253 = new Docente("Ruperto", "Barros Quintana", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d254 = new Docente("Silvestra", "Mesa Córdoba", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d255 = new Docente("Teófilo", "Valverde Pizarro", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d256 = new Docente("Urbano", "Lagos Espinosa", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d257 = new Docente("Viviana", "Maldonado Rivas", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d258 = new Docente("Wilfredo", "Carrasco Lago", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d259 = new Docente("Xenia", "Roldán Páez", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d260 = new Docente("Yolando", "Sarmiento Montes", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d261 = new Docente("Zacarías", "Vega Otero", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d262 = new Docente("Adela", "Galindo Valle", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d263 = new Docente("Baldomero", "Castañeda Ríos", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d264 = new Docente("Carmelo", "Miranda Lago", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d265 = new Docente("Dolores", "Aguirre Pino", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d266 = new Docente("Eleuterio", "Solano Roldán", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d267 = new Docente("Fidencia", "Montenegro Páez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d268 = new Docente("Gervasio", "Cervantes Espinoza", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d269 = new Docente("Honorina", "Ojeda Valdivia", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d270 = new Docente("Inocencio", "Lara Montesinos", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d271 = new Docente("Jacinto", "Méndez Ríos", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d272 = new Docente("Leocadia", "Cortés Ocampo", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d273 = new Docente("Macario", "Peralta Villalba", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d274 = new Docente("Natalia", "Ríos Zambrano", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d275 = new Docente("Olegario", "Montes Pizarro", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d276 = new Docente("Pacífica", "Alarcón Narváez", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d277 = new Docente("Quirino", "Quintana Barros", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d278 = new Docente("Rosalía", "Córdoba Mesa", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d279 = new Docente("Saturnino", "Valverde Lagos", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d280 = new Docente("Teodosia", "Espinosa Maldonado", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d281 = new Docente("Ulpiano", "Rivas Carrasco", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d282 = new Docente("Venancia", "Lago Roldán", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d283 = new Docente("Wenceslao", "Páez Sarmiento", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d284 = new Docente("Xenia", "Montes Vega", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d285 = new Docente("Yago", "Valle Galindo", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d286 = new Docente("Zoraida", "Ríos Castañeda", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d287 = new Docente("Adelio", "Lago Miranda", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d288 = new Docente("Berta", "Pino Aguirre", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);
				Docente d289 = new Docente("Celso", "Roldán Solano", CategoriaCientifica.NINGUNA, CategoriaDocente.INSTRUCTOR);
				Docente d290 = new Docente("Dina", "Páez Montenegro", CategoriaCientifica.MASTER, CategoriaDocente.ASISTENTE);
				Docente d291 = new Docente("Eligio", "Espinoza Cervantes", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d292 = new Docente("Fabiola", "Valdivia Ojeda", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_TITULAR);
				Docente d293 = new Docente("Galo", "Montesinos Lara", CategoriaCientifica.MASTER, CategoriaDocente.INSTRUCTOR);
				Docente d294 = new Docente("Herminia", "Ríos Méndez", CategoriaCientifica.DOCTOR, CategoriaDocente.ASISTENTE);
				Docente d295 = new Docente("Inocencio", "Ocampo Cortés", CategoriaCientifica.NINGUNA, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d296 = new Docente("Jovita", "Villalba Peralta", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_TITULAR);
				Docente d297 = new Docente("Lauro", "Zambrano Ríos", CategoriaCientifica.DOCTOR, CategoriaDocente.INSTRUCTOR);
				Docente d298 = new Docente("Melania", "Pizarro Montes", CategoriaCientifica.NINGUNA, CategoriaDocente.ASISTENTE);
				Docente d299 = new Docente("Narciso", "Narváez Alarcón", CategoriaCientifica.MASTER, CategoriaDocente.PROFESOR_AUXILIAR);
				Docente d300 = new Docente("Otilio", "Barros Quintana", CategoriaCientifica.DOCTOR, CategoriaDocente.PROFESOR_TITULAR);

				vicedecanato.agregarDocente(d1); vicedecanato.agregarDocente(d2); vicedecanato.agregarDocente(d3);
				vicedecanato.agregarDocente(d4); vicedecanato.agregarDocente(d5); vicedecanato.agregarDocente(d6);
				vicedecanato.agregarDocente(d7); vicedecanato.agregarDocente(d8); vicedecanato.agregarDocente(d9);
				vicedecanato.agregarDocente(d10); vicedecanato.agregarDocente(d11); vicedecanato.agregarDocente(d12);
				vicedecanato.agregarDocente(d13); vicedecanato.agregarDocente(d14); vicedecanato.agregarDocente(d15);
				vicedecanato.agregarDocente(d16); vicedecanato.agregarDocente(d17); vicedecanato.agregarDocente(d18);
				vicedecanato.agregarDocente(d19); vicedecanato.agregarDocente(d20); vicedecanato.agregarDocente(d21);
				vicedecanato.agregarDocente(d22); vicedecanato.agregarDocente(d23); vicedecanato.agregarDocente(d24);
				vicedecanato.agregarDocente(d25); vicedecanato.agregarDocente(d26); vicedecanato.agregarDocente(d27);
				vicedecanato.agregarDocente(d28); vicedecanato.agregarDocente(d29); vicedecanato.agregarDocente(d30);
				vicedecanato.agregarDocente(d31); vicedecanato.agregarDocente(d32); vicedecanato.agregarDocente(d33);
				vicedecanato.agregarDocente(d34); vicedecanato.agregarDocente(d35); vicedecanato.agregarDocente(d36);
				vicedecanato.agregarDocente(d37); vicedecanato.agregarDocente(d38); vicedecanato.agregarDocente(d39);
				vicedecanato.agregarDocente(d40); vicedecanato.agregarDocente(d41); vicedecanato.agregarDocente(d42);
				vicedecanato.agregarDocente(d43); vicedecanato.agregarDocente(d44); vicedecanato.agregarDocente(d45);
				vicedecanato.agregarDocente(d46); vicedecanato.agregarDocente(d47); vicedecanato.agregarDocente(d48);
				vicedecanato.agregarDocente(d49); vicedecanato.agregarDocente(d50); vicedecanato.agregarDocente(d51);
				vicedecanato.agregarDocente(d52); vicedecanato.agregarDocente(d53); vicedecanato.agregarDocente(d54);
				vicedecanato.agregarDocente(d55); vicedecanato.agregarDocente(d56); vicedecanato.agregarDocente(d57);
				vicedecanato.agregarDocente(d58); vicedecanato.agregarDocente(d59); vicedecanato.agregarDocente(d60);
				vicedecanato.agregarDocente(d61); vicedecanato.agregarDocente(d62); vicedecanato.agregarDocente(d63);
				vicedecanato.agregarDocente(d64); vicedecanato.agregarDocente(d65); vicedecanato.agregarDocente(d66);
				vicedecanato.agregarDocente(d67); vicedecanato.agregarDocente(d68); vicedecanato.agregarDocente(d69);
				vicedecanato.agregarDocente(d70); vicedecanato.agregarDocente(d71); vicedecanato.agregarDocente(d72);
				vicedecanato.agregarDocente(d73); vicedecanato.agregarDocente(d74); vicedecanato.agregarDocente(d75);
				vicedecanato.agregarDocente(d76); vicedecanato.agregarDocente(d77); vicedecanato.agregarDocente(d78);
				vicedecanato.agregarDocente(d79); vicedecanato.agregarDocente(d80); vicedecanato.agregarDocente(d81);
				vicedecanato.agregarDocente(d82); vicedecanato.agregarDocente(d83); vicedecanato.agregarDocente(d84);
				vicedecanato.agregarDocente(d85); vicedecanato.agregarDocente(d86); vicedecanato.agregarDocente(d87);
				vicedecanato.agregarDocente(d88); vicedecanato.agregarDocente(d89); vicedecanato.agregarDocente(d90);
				vicedecanato.agregarDocente(d91); vicedecanato.agregarDocente(d92); vicedecanato.agregarDocente(d93);
				vicedecanato.agregarDocente(d94); vicedecanato.agregarDocente(d95); vicedecanato.agregarDocente(d96);
				vicedecanato.agregarDocente(d97); vicedecanato.agregarDocente(d98); vicedecanato.agregarDocente(d99);
				vicedecanato.agregarDocente(d100); vicedecanato.agregarDocente(d101); vicedecanato.agregarDocente(d102);
				vicedecanato.agregarDocente(d103); vicedecanato.agregarDocente(d104); vicedecanato.agregarDocente(d105);
				vicedecanato.agregarDocente(d106); vicedecanato.agregarDocente(d107); vicedecanato.agregarDocente(d108);
				vicedecanato.agregarDocente(d109); vicedecanato.agregarDocente(d110); vicedecanato.agregarDocente(d111);
				vicedecanato.agregarDocente(d112); vicedecanato.agregarDocente(d113); vicedecanato.agregarDocente(d114);
				vicedecanato.agregarDocente(d115); vicedecanato.agregarDocente(d116); vicedecanato.agregarDocente(d117);
				vicedecanato.agregarDocente(d118); vicedecanato.agregarDocente(d119); vicedecanato.agregarDocente(d120);
				vicedecanato.agregarDocente(d121); vicedecanato.agregarDocente(d122); vicedecanato.agregarDocente(d123);
				vicedecanato.agregarDocente(d124); vicedecanato.agregarDocente(d125); vicedecanato.agregarDocente(d126);
				vicedecanato.agregarDocente(d127); vicedecanato.agregarDocente(d128); vicedecanato.agregarDocente(d129);
				vicedecanato.agregarDocente(d130); vicedecanato.agregarDocente(d131); vicedecanato.agregarDocente(d132);
				vicedecanato.agregarDocente(d133); vicedecanato.agregarDocente(d134); vicedecanato.agregarDocente(d135);
				vicedecanato.agregarDocente(d136); vicedecanato.agregarDocente(d137); vicedecanato.agregarDocente(d138);
				vicedecanato.agregarDocente(d139); vicedecanato.agregarDocente(d140); vicedecanato.agregarDocente(d141);
				vicedecanato.agregarDocente(d142); vicedecanato.agregarDocente(d143); vicedecanato.agregarDocente(d144);
				vicedecanato.agregarDocente(d145); vicedecanato.agregarDocente(d146); vicedecanato.agregarDocente(d147);
				vicedecanato.agregarDocente(d148); vicedecanato.agregarDocente(d149); vicedecanato.agregarDocente(d150);
				vicedecanato.agregarDocente(d151); vicedecanato.agregarDocente(d152); vicedecanato.agregarDocente(d153);
				vicedecanato.agregarDocente(d154); vicedecanato.agregarDocente(d155); vicedecanato.agregarDocente(d156);
				vicedecanato.agregarDocente(d157); vicedecanato.agregarDocente(d158); vicedecanato.agregarDocente(d159);
				vicedecanato.agregarDocente(d160); vicedecanato.agregarDocente(d161); vicedecanato.agregarDocente(d162);
				vicedecanato.agregarDocente(d163); vicedecanato.agregarDocente(d164); vicedecanato.agregarDocente(d165);
				vicedecanato.agregarDocente(d166); vicedecanato.agregarDocente(d167); vicedecanato.agregarDocente(d168);
				vicedecanato.agregarDocente(d169); vicedecanato.agregarDocente(d170); vicedecanato.agregarDocente(d171);
				vicedecanato.agregarDocente(d172); vicedecanato.agregarDocente(d173); vicedecanato.agregarDocente(d174);
				vicedecanato.agregarDocente(d175); vicedecanato.agregarDocente(d176); vicedecanato.agregarDocente(d177);
				vicedecanato.agregarDocente(d178); vicedecanato.agregarDocente(d179); vicedecanato.agregarDocente(d180);
				vicedecanato.agregarDocente(d181); vicedecanato.agregarDocente(d182); vicedecanato.agregarDocente(d183);
				vicedecanato.agregarDocente(d184); vicedecanato.agregarDocente(d185); vicedecanato.agregarDocente(d186);
				vicedecanato.agregarDocente(d187); vicedecanato.agregarDocente(d188); vicedecanato.agregarDocente(d189);
				vicedecanato.agregarDocente(d190); vicedecanato.agregarDocente(d191); vicedecanato.agregarDocente(d192);
				vicedecanato.agregarDocente(d193); vicedecanato.agregarDocente(d194); vicedecanato.agregarDocente(d195);
				vicedecanato.agregarDocente(d196); vicedecanato.agregarDocente(d197); vicedecanato.agregarDocente(d198);
				vicedecanato.agregarDocente(d199); vicedecanato.agregarDocente(d200); vicedecanato.agregarDocente(d201);
				vicedecanato.agregarDocente(d202); vicedecanato.agregarDocente(d203); vicedecanato.agregarDocente(d204);
				vicedecanato.agregarDocente(d205); vicedecanato.agregarDocente(d206); vicedecanato.agregarDocente(d207);
				vicedecanato.agregarDocente(d208); vicedecanato.agregarDocente(d209); vicedecanato.agregarDocente(d210);
				vicedecanato.agregarDocente(d211); vicedecanato.agregarDocente(d212); vicedecanato.agregarDocente(d213);
				vicedecanato.agregarDocente(d214); vicedecanato.agregarDocente(d215); vicedecanato.agregarDocente(d216);
				vicedecanato.agregarDocente(d217); vicedecanato.agregarDocente(d218); vicedecanato.agregarDocente(d219);
				vicedecanato.agregarDocente(d220); vicedecanato.agregarDocente(d221); vicedecanato.agregarDocente(d222);
				vicedecanato.agregarDocente(d223); vicedecanato.agregarDocente(d224); vicedecanato.agregarDocente(d225);
				vicedecanato.agregarDocente(d226); vicedecanato.agregarDocente(d227); vicedecanato.agregarDocente(d228);
				vicedecanato.agregarDocente(d229); vicedecanato.agregarDocente(d230); vicedecanato.agregarDocente(d231);
				vicedecanato.agregarDocente(d232); vicedecanato.agregarDocente(d233); vicedecanato.agregarDocente(d234);
				vicedecanato.agregarDocente(d235); vicedecanato.agregarDocente(d236); vicedecanato.agregarDocente(d237);
				vicedecanato.agregarDocente(d238); vicedecanato.agregarDocente(d239); vicedecanato.agregarDocente(d240);
				vicedecanato.agregarDocente(d241); vicedecanato.agregarDocente(d242); vicedecanato.agregarDocente(d243);
				vicedecanato.agregarDocente(d244); vicedecanato.agregarDocente(d245); vicedecanato.agregarDocente(d246);
				vicedecanato.agregarDocente(d247); vicedecanato.agregarDocente(d248); vicedecanato.agregarDocente(d249);
				vicedecanato.agregarDocente(d250); vicedecanato.agregarDocente(d251); vicedecanato.agregarDocente(d252);
				vicedecanato.agregarDocente(d253); vicedecanato.agregarDocente(d254); vicedecanato.agregarDocente(d255);
				vicedecanato.agregarDocente(d256); vicedecanato.agregarDocente(d257); vicedecanato.agregarDocente(d258);
				vicedecanato.agregarDocente(d259); vicedecanato.agregarDocente(d260); vicedecanato.agregarDocente(d261);
				vicedecanato.agregarDocente(d262); vicedecanato.agregarDocente(d263); vicedecanato.agregarDocente(d264);
				vicedecanato.agregarDocente(d265); vicedecanato.agregarDocente(d266); vicedecanato.agregarDocente(d267);
				vicedecanato.agregarDocente(d268); vicedecanato.agregarDocente(d269); vicedecanato.agregarDocente(d270);
				vicedecanato.agregarDocente(d271); vicedecanato.agregarDocente(d272); vicedecanato.agregarDocente(d273);
				vicedecanato.agregarDocente(d274); vicedecanato.agregarDocente(d275); vicedecanato.agregarDocente(d276);
				vicedecanato.agregarDocente(d277); vicedecanato.agregarDocente(d278); vicedecanato.agregarDocente(d279);
				vicedecanato.agregarDocente(d280); vicedecanato.agregarDocente(d281); vicedecanato.agregarDocente(d282);
				vicedecanato.agregarDocente(d283); vicedecanato.agregarDocente(d284); vicedecanato.agregarDocente(d285);
				vicedecanato.agregarDocente(d286); vicedecanato.agregarDocente(d287); vicedecanato.agregarDocente(d288);
				vicedecanato.agregarDocente(d289); vicedecanato.agregarDocente(d290); vicedecanato.agregarDocente(d291);
				vicedecanato.agregarDocente(d292); vicedecanato.agregarDocente(d293); vicedecanato.agregarDocente(d294);
				vicedecanato.agregarDocente(d295); vicedecanato.agregarDocente(d296); vicedecanato.agregarDocente(d297);
				vicedecanato.agregarDocente(d298); vicedecanato.agregarDocente(d299); vicedecanato.agregarDocente(d300);

				depto1.agregarDocente(d1); depto1.agregarDocente(d2); depto1.agregarDocente(d3); depto1.agregarDocente(d4); 
				depto1.agregarDocente(d5); depto1.agregarDocente(d6); depto1.agregarDocente(d7); depto1.agregarDocente(d8); 
				depto1.agregarDocente(d9); depto1.agregarDocente(d10); depto1.agregarDocente(d11); depto1.agregarDocente(d12); 
				depto1.agregarDocente(d13); depto1.agregarDocente(d14); depto1.agregarDocente(d15); depto1.agregarDocente(d16); 
				depto1.agregarDocente(d17); depto1.agregarDocente(d18); depto1.agregarDocente(d19); depto1.agregarDocente(d20); 
				depto1.agregarDocente(d21); depto1.agregarDocente(d22); depto1.agregarDocente(d23); depto1.agregarDocente(d24); 
				depto1.agregarDocente(d25); depto1.agregarDocente(d26); depto1.agregarDocente(d27); depto1.agregarDocente(d28); 
				depto1.agregarDocente(d29); depto1.agregarDocente(d30); depto1.agregarDocente(d31); depto1.agregarDocente(d32); 
				depto1.agregarDocente(d33); depto1.agregarDocente(d34); depto1.agregarDocente(d35); depto1.agregarDocente(d36); 
				depto1.agregarDocente(d37); depto1.agregarDocente(d38); depto1.agregarDocente(d39); depto1.agregarDocente(d40); 
				depto1.agregarDocente(d41); depto1.agregarDocente(d42); depto1.agregarDocente(d43); depto1.agregarDocente(d44); 
				depto1.agregarDocente(d45); depto1.agregarDocente(d46); depto1.agregarDocente(d47); depto1.agregarDocente(d48); 
				depto1.agregarDocente(d49); depto1.agregarDocente(d50); depto1.agregarDocente(d51); depto1.agregarDocente(d52); 
				depto1.agregarDocente(d53); depto1.agregarDocente(d54); depto1.agregarDocente(d55); depto1.agregarDocente(d56); 
				depto1.agregarDocente(d57); depto1.agregarDocente(d58); depto1.agregarDocente(d59); depto1.agregarDocente(d60); 
				depto1.agregarDocente(d61); depto1.agregarDocente(d62); depto1.agregarDocente(d63); depto1.agregarDocente(d64); 
				depto1.agregarDocente(d65); depto1.agregarDocente(d66); depto1.agregarDocente(d67); depto1.agregarDocente(d68); 
				depto1.agregarDocente(d69); depto1.agregarDocente(d70); depto1.agregarDocente(d71); depto1.agregarDocente(d72); 
				depto1.agregarDocente(d73); depto1.agregarDocente(d74); depto1.agregarDocente(d75); depto1.agregarDocente(d76); 
				depto1.agregarDocente(d77); depto1.agregarDocente(d78); depto1.agregarDocente(d79); depto1.agregarDocente(d80); 
				depto1.agregarDocente(d81); depto1.agregarDocente(d82); depto1.agregarDocente(d83); depto1.agregarDocente(d84); 
				depto1.agregarDocente(d85); depto1.agregarDocente(d86); depto1.agregarDocente(d87); depto1.agregarDocente(d88); 
				depto1.agregarDocente(d89); depto1.agregarDocente(d90); depto1.agregarDocente(d91); depto1.agregarDocente(d92); 
				depto1.agregarDocente(d93); depto1.agregarDocente(d94); depto1.agregarDocente(d95); depto1.agregarDocente(d96); 
				depto1.agregarDocente(d97); depto1.agregarDocente(d98); depto1.agregarDocente(d99); depto1.agregarDocente(d100);

				depto2.agregarDocente(d101); depto2.agregarDocente(d102); depto2.agregarDocente(d103); depto2.agregarDocente(d104); 
				depto2.agregarDocente(d105); depto2.agregarDocente(d106); depto2.agregarDocente(d107); depto2.agregarDocente(d108); 
				depto2.agregarDocente(d109); depto2.agregarDocente(d110); depto2.agregarDocente(d111); depto2.agregarDocente(d112); 
				depto2.agregarDocente(d113); depto2.agregarDocente(d114); depto2.agregarDocente(d115); depto2.agregarDocente(d116); 
				depto2.agregarDocente(d117); depto2.agregarDocente(d118); depto2.agregarDocente(d119); depto2.agregarDocente(d120); 
				depto2.agregarDocente(d121); depto2.agregarDocente(d122); depto2.agregarDocente(d123); depto2.agregarDocente(d124); 
				depto2.agregarDocente(d125); depto2.agregarDocente(d126); depto2.agregarDocente(d127); depto2.agregarDocente(d128); 
				depto2.agregarDocente(d129); depto2.agregarDocente(d130); depto2.agregarDocente(d131); depto2.agregarDocente(d132); 
				depto2.agregarDocente(d133); depto2.agregarDocente(d134); depto2.agregarDocente(d135); depto2.agregarDocente(d136); 
				depto2.agregarDocente(d137); depto2.agregarDocente(d138); depto2.agregarDocente(d139); depto2.agregarDocente(d140); 
				depto2.agregarDocente(d141); depto2.agregarDocente(d142); depto2.agregarDocente(d143); depto2.agregarDocente(d144); 
				depto2.agregarDocente(d145); depto2.agregarDocente(d146); depto2.agregarDocente(d147); depto2.agregarDocente(d148); 
				depto2.agregarDocente(d149); depto2.agregarDocente(d150); depto2.agregarDocente(d151); depto2.agregarDocente(d152); 
				depto2.agregarDocente(d153); depto2.agregarDocente(d154); depto2.agregarDocente(d155); depto2.agregarDocente(d156); 
				depto2.agregarDocente(d157); depto2.agregarDocente(d158); depto2.agregarDocente(d159); depto2.agregarDocente(d160); 
				depto2.agregarDocente(d161); depto2.agregarDocente(d162); depto2.agregarDocente(d163); depto2.agregarDocente(d164); 
				depto2.agregarDocente(d165); depto2.agregarDocente(d166); depto2.agregarDocente(d167); depto2.agregarDocente(d168); 
				depto2.agregarDocente(d169); depto2.agregarDocente(d170); depto2.agregarDocente(d171); depto2.agregarDocente(d172); 
				depto2.agregarDocente(d173); depto2.agregarDocente(d174); depto2.agregarDocente(d175); depto2.agregarDocente(d176); 
				depto2.agregarDocente(d177); depto2.agregarDocente(d178); depto2.agregarDocente(d179); depto2.agregarDocente(d180); 
				depto2.agregarDocente(d181); depto2.agregarDocente(d182); depto2.agregarDocente(d183); depto2.agregarDocente(d184); 
				depto2.agregarDocente(d185); depto2.agregarDocente(d186); depto2.agregarDocente(d187); depto2.agregarDocente(d188); 
				depto2.agregarDocente(d189); depto2.agregarDocente(d190); depto2.agregarDocente(d191); depto2.agregarDocente(d192); 
				depto2.agregarDocente(d193); depto2.agregarDocente(d194); depto2.agregarDocente(d195); depto2.agregarDocente(d196); 
				depto2.agregarDocente(d197); depto2.agregarDocente(d198); depto2.agregarDocente(d199); depto2.agregarDocente(d200);

				depto3.agregarDocente(d201); depto3.agregarDocente(d202); depto3.agregarDocente(d203); depto3.agregarDocente(d204); 
				depto3.agregarDocente(d205); depto3.agregarDocente(d206); depto3.agregarDocente(d207); depto3.agregarDocente(d208); 
				depto3.agregarDocente(d209); depto3.agregarDocente(d210); depto3.agregarDocente(d211); depto3.agregarDocente(d212); 
				depto3.agregarDocente(d213); depto3.agregarDocente(d214); depto3.agregarDocente(d215); depto3.agregarDocente(d216); 
				depto3.agregarDocente(d217); depto3.agregarDocente(d218); depto3.agregarDocente(d219); depto3.agregarDocente(d220); 
				depto3.agregarDocente(d221); depto3.agregarDocente(d222); depto3.agregarDocente(d223); depto3.agregarDocente(d224); 
				depto3.agregarDocente(d225); depto3.agregarDocente(d226); depto3.agregarDocente(d227); depto3.agregarDocente(d228); 
				depto3.agregarDocente(d229); depto3.agregarDocente(d230); depto3.agregarDocente(d231); depto3.agregarDocente(d232); 
				depto3.agregarDocente(d233); depto3.agregarDocente(d234); depto3.agregarDocente(d235); depto3.agregarDocente(d236); 
				depto3.agregarDocente(d237); depto3.agregarDocente(d238); depto3.agregarDocente(d239); depto3.agregarDocente(d240); 
				depto3.agregarDocente(d241); depto3.agregarDocente(d242); depto3.agregarDocente(d243); depto3.agregarDocente(d244); 
				depto3.agregarDocente(d245); depto3.agregarDocente(d246); depto3.agregarDocente(d247); depto3.agregarDocente(d248); 
				depto3.agregarDocente(d249); depto3.agregarDocente(d250); depto3.agregarDocente(d251); depto3.agregarDocente(d252); 
				depto3.agregarDocente(d253); depto3.agregarDocente(d254); depto3.agregarDocente(d255); depto3.agregarDocente(d256); 
				depto3.agregarDocente(d257); depto3.agregarDocente(d258); depto3.agregarDocente(d259); depto3.agregarDocente(d260); 
				depto3.agregarDocente(d261); depto3.agregarDocente(d262); depto3.agregarDocente(d263); depto3.agregarDocente(d264); 
				depto3.agregarDocente(d265); depto3.agregarDocente(d266); depto3.agregarDocente(d267); depto3.agregarDocente(d268); 
				depto3.agregarDocente(d269); depto3.agregarDocente(d270); depto3.agregarDocente(d271); depto3.agregarDocente(d272); 
				depto3.agregarDocente(d273); depto3.agregarDocente(d274); depto3.agregarDocente(d275); depto3.agregarDocente(d276); 
				depto3.agregarDocente(d277); depto3.agregarDocente(d278); depto3.agregarDocente(d279); depto3.agregarDocente(d280); 
				depto3.agregarDocente(d281); depto3.agregarDocente(d282); depto3.agregarDocente(d283); depto3.agregarDocente(d284); 
				depto3.agregarDocente(d285); depto3.agregarDocente(d286); depto3.agregarDocente(d287); depto3.agregarDocente(d288); 
				depto3.agregarDocente(d289); depto3.agregarDocente(d290); depto3.agregarDocente(d291); depto3.agregarDocente(d292); 
				depto3.agregarDocente(d293); depto3.agregarDocente(d294); depto3.agregarDocente(d295); depto3.agregarDocente(d296); 
				depto3.agregarDocente(d297); depto3.agregarDocente(d298); depto3.agregarDocente(d299); depto3.agregarDocente(d300);

				//Aqui se crean los estudiantes y se agregan
				Estudiante e1 = new Estudiante("Ryan", "Negrete Menchaca", "Grupo de Investigación A");
				Estudiante e2 = new Estudiante("Mariana", "Santos", "Grupo de Investigación B");
				Estudiante e3 = new Estudiante("Roberto", "Vera", "Grupo de Investigación C");
				Estudiante e4 = new Estudiante("Carla", "Cabrera", "Grupo de Investigación D");
				Estudiante e5 = new Estudiante("Ignacio", "Rojas", "Grupo de Investigación E");
				Estudiante e6 = new Estudiante("Daniela", "Espinoza", "Grupo de Investigación F");
				Estudiante e7 = new Estudiante("Tomás", "Vidal", "Grupo de Investigación G");
				Estudiante e8 = new Estudiante("Florencia", "Tapia", "Grupo de Investigación H");
				Estudiante e9 = new Estudiante("Esteban", "Carrillo", "Grupo de Investigación I");
				Estudiante e10 = new Estudiante("Valentina", "Contreras", "Grupo de Investigación J");
				Estudiante e11 = new Estudiante("Matías", "Pastor", "Grupo de Investigación K");
				Estudiante e12 = new Estudiante("Catalina", "Pinto", "Grupo de Investigación L");
				Estudiante e13 = new Estudiante("Lian Carlos", "Gené Galvez", "Grupo de Investigación M");
				Estudiante e14 = new Estudiante("Lucía", "Parra", "Grupo de Investigación N");
				Estudiante e15 = new Estudiante("Sergio", "Delgado", "Grupo de Investigación O");
				Estudiante e16 = new Estudiante("Camila", "Soto", "Grupo de Investigación P");
				Estudiante e17 = new Estudiante("Andrés", "Mora", "Grupo de Investigación Q");
				Estudiante e18 = new Estudiante("Antonia", "Fuentes", "Grupo de Investigación R");
				Estudiante e19 = new Estudiante("Nicolás", "Cisterna", "Grupo de Investigación S");
				Estudiante e20 = new Estudiante("Javiera", "Godoy", "Grupo de Investigación T");
				Estudiante e21 = new Estudiante("Francisco", "Araya", "Grupo de Investigación U");
				Estudiante e22 = new Estudiante("Macarena", "Sepúlveda", "Grupo de Investigación V");
				Estudiante e23 = new Estudiante("Rodrigo", "Cerda", "Grupo de Investigación W");
				Estudiante e24 = new Estudiante("Belén", "Méndez", "Grupo de Investigación X");
				Estudiante e25 = new Estudiante("Gabriel", "Urrutia", "Grupo de Investigación Y");
				Estudiante e26 = new Estudiante("Constanza", "Navarro", "Grupo de Investigación Z");
				Estudiante e27 = new Estudiante("Cristóbal", "Cordero", "Grupo de Investigación A");
				Estudiante e28 = new Estudiante("Barbara", "Munizaga", "Grupo de Investigación B");
				Estudiante e29 = new Estudiante("Juan", "Figueroa", "Grupo de Investigación C");
				Estudiante e30 = new Estudiante("Isabel", "Poblete", "Grupo de Investigación D");
				Estudiante e31 = new Estudiante("Rafael", "Mardones", "Grupo de Investigación E");
				Estudiante e32 = new Estudiante("Tamara", "Cid", "Grupo de Investigación F");
				Estudiante e33 = new Estudiante("Sebastián", "Carrasco", "Grupo de Investigación G");
				Estudiante e34 = new Estudiante("Valeria", "Flores", "Grupo de Investigación H");
				Estudiante e35 = new Estudiante("Diego", "Gálvez", "Grupo de Investigación I");
				Estudiante e36 = new Estudiante("Carmen", "Moyano", "Grupo de Investigación J");
				Estudiante e37 = new Estudiante("Ignacio", "Guzmán", "Grupo de Investigación K");
				Estudiante e38 = new Estudiante("Marcelo", "Lagos", "Grupo de Investigación L");
				Estudiante e39 = new Estudiante("Ximena", "Riquelme", "Grupo de Investigación M");
				Estudiante e40 = new Estudiante("Cristina", "Vargas", "Grupo de Investigación N");

				vicedecanato.agregarEstudiante(e1); vicedecanato.agregarEstudiante(e2); vicedecanato.agregarEstudiante(e3);
				vicedecanato.agregarEstudiante(e4); vicedecanato.agregarEstudiante(e5); vicedecanato.agregarEstudiante(e6);
				vicedecanato.agregarEstudiante(e7); vicedecanato.agregarEstudiante(e8); vicedecanato.agregarEstudiante(e9);
				vicedecanato.agregarEstudiante(e10); vicedecanato.agregarEstudiante(e11); vicedecanato.agregarEstudiante(e12);
				vicedecanato.agregarEstudiante(e13); vicedecanato.agregarEstudiante(e14); vicedecanato.agregarEstudiante(e15);
				vicedecanato.agregarEstudiante(e16); vicedecanato.agregarEstudiante(e17); vicedecanato.agregarEstudiante(e18);
				vicedecanato.agregarEstudiante(e19); vicedecanato.agregarEstudiante(e20); vicedecanato.agregarEstudiante(e21);
				vicedecanato.agregarEstudiante(e22); vicedecanato.agregarEstudiante(e23); vicedecanato.agregarEstudiante(e24);
				vicedecanato.agregarEstudiante(e25); vicedecanato.agregarEstudiante(e26); vicedecanato.agregarEstudiante(e27);
				vicedecanato.agregarEstudiante(e28); vicedecanato.agregarEstudiante(e29); vicedecanato.agregarEstudiante(e30);
				vicedecanato.agregarEstudiante(e31); vicedecanato.agregarEstudiante(e32); vicedecanato.agregarEstudiante(e33);
				vicedecanato.agregarEstudiante(e34); vicedecanato.agregarEstudiante(e35); vicedecanato.agregarEstudiante(e36);
				vicedecanato.agregarEstudiante(e37); vicedecanato.agregarEstudiante(e38); vicedecanato.agregarEstudiante(e39);
				vicedecanato.agregarEstudiante(e40);

				depto1.agregarEstudiante(e1); 
				depto1.agregarEstudiante(e2); 
				depto1.agregarEstudiante(e3);
				depto1.agregarEstudiante(e4); 
				depto1.agregarEstudiante(e5); 
				depto1.agregarEstudiante(e6);
				depto1.agregarEstudiante(e7); 
				depto1.agregarEstudiante(e8); 
				depto1.agregarEstudiante(e9);
				depto1.agregarEstudiante(e10); 
				depto1.agregarEstudiante(e11); 
				depto1.agregarEstudiante(e12);
				depto1.agregarEstudiante(e13); 
				
				depto2.agregarEstudiante(e14); 
				depto2.agregarEstudiante(e15);
				depto2.agregarEstudiante(e16); 
				depto2.agregarEstudiante(e17); 
				depto2.agregarEstudiante(e18);
				depto2.agregarEstudiante(e19); 
				depto2.agregarEstudiante(e20); 
				depto2.agregarEstudiante(e21); 
				depto2.agregarEstudiante(e22); 
				depto2.agregarEstudiante(e23);
				depto2.agregarEstudiante(e24); 
				depto2.agregarEstudiante(e25); 
				depto2.agregarEstudiante(e26);
				depto2.agregarEstudiante(e27); 
				
				depto3.agregarEstudiante(e28); 
				depto3.agregarEstudiante(e29);
				depto3.agregarEstudiante(e30); 
				depto3.agregarEstudiante(e31); 
				depto3.agregarEstudiante(e32);
				depto3.agregarEstudiante(e33); 
				depto3.agregarEstudiante(e34); 
				depto3.agregarEstudiante(e35);
				depto3.agregarEstudiante(e36); 
				depto3.agregarEstudiante(e37); 
				depto3.agregarEstudiante(e38);
				depto3.agregarEstudiante(e39); 
				depto3.agregarEstudiante(e40);

				//Maestrias del departamento 1
				Maestria m1d1 = new Maestria("Maestría en Inteligencia Artificial", 24, "Ciencias de la Computación");
				Maestria m2d1 = new Maestria("Maestría en Ciberseguridad y Redes", 18,"Seguridad Informática");
				Maestria m3d1 = new Maestria("Maestría en Ciencia de Datos", 24, "Análisis de Datos");

				depto1.agregarMaestria(m1d1); 
				depto1.agregarMaestria(m2d1); 
				depto1.agregarMaestria(m3d1);

				//Maestrias del departamento 2
				Maestria m1d2 = new Maestria("Maestría en Sistemas de Potencia", 24, "Energía Eléctrica");
				Maestria m2d2 = new Maestria("Maestría en Automatización Industrial", 18, "Control de Procesos");
				Maestria m3d2 = new Maestria("Maestría en Telecomunicaciones", 24, "Comunicaciones Digitales");
				Maestria m4d2 = new Maestria("Maestría en Electrónica de Potencia", 18, "Electrónica Industrial");

				depto2.agregarMaestria(m1d2); 
				depto2.agregarMaestria(m2d2); 
				depto2.agregarMaestria(m3d2); 
				depto2.agregarMaestria(m4d2);

				//Maestrias del departamento 3
				Maestria m1d3 = new Maestria("Maestría en Matemática Aplicada", 24, "Modelos Matemáticos");
				Maestria m2d3 = new Maestria("Maestría en Estadística Avanzada", 18, "Análisis Estadístico");
				Maestria m3d3 = new Maestria("Maestría en Investigación Operativa", 24, "Optimización Matemática");
				Maestria m4d3 = new Maestria("Maestría en Matemática Financiera", 18, "Modelos Financieros");
				Maestria m5d3 = new Maestria("Maestría en Criptografía", 24, "Seguridad Matemática");

				depto3.agregarMaestria(m1d3); 
				depto3.agregarMaestria(m2d3); 
				depto3.agregarMaestria(m3d3); 
				depto3.agregarMaestria(m4d3); 
				depto3.agregarMaestria(m5d3);

				//Cursos de la maestria 1 del departamento 1
				CursoPosgrado c1m1d1 = new CursoPosgrado("Fundamentos de Inteligencia Artificial", new ArrayList<String>() {{ add("Comprender los fundamentos teóricos de la IA"); add("Aplicar algoritmos de aprendizaje automático"); }}, 4, d1);
				CursoPosgrado c2m1d1 = new CursoPosgrado("Redes Neuronales y Deep Learning", new ArrayList<String>() {{ add("Desarrollar modelos de redes neuronales"); add("Implementar soluciones de deep learning"); }}, 5, d6);
				CursoPosgrado c3m1d1 = new CursoPosgrado("Procesamiento de Lenguaje Natural", new ArrayList<String>() {{ add("Analizar problemas de procesamiento de lenguaje natural"); add("Implementar soluciones de NLP");}}, 4, d11);
				CursoPosgrado c4m1d1 = new CursoPosgrado("Visión por Computadora", new ArrayList<String>() {{add("Entender los principios de visión por computadora");add("Desarrollar aplicaciones de reconocimiento de imágenes"); }}, 5, d16);

				m1d1.agregarCursoPosgrado(c1m1d1);
				m1d1.agregarCursoPosgrado(c2m1d1);
				m1d1.agregarCursoPosgrado(c3m1d1);
				m1d1.agregarCursoPosgrado(c4m1d1);

				//Cursos de la maestria 2 del departamento 1
				CursoPosgrado c1m2d1 = new CursoPosgrado("Fundamentos de Ciberseguridad", new ArrayList<String>() {{ add("Comprender los principios de seguridad informática"); add("Analizar vulnerabilidades en sistemas"); }}, 4, d3);
				CursoPosgrado c2m2d1 = new CursoPosgrado("Criptografía Avanzada", new ArrayList<String>() {{ add("Implementar técnicas de criptografía moderna"); add("Analizar protocolos de seguridad"); }}, 5, d8);
				CursoPosgrado c3m2d1 = new CursoPosgrado("Seguridad en Redes", new ArrayList<String>() {{ add("Identificar amenazas en redes"); add("Diseñar redes seguras"); }}, 4, d13);

				m2d1.agregarCursoPosgrado(c1m2d1);
				m2d1.agregarCursoPosgrado(c2m2d1);
				m2d1.agregarCursoPosgrado(c3m2d1);

				//Cursos de la maestria 3 del departamento 1
				CursoPosgrado c1m3d1 = new CursoPosgrado("Análisis Exploratorio de Datos", new ArrayList<String>() {{ add("Manejar técnicas de análisis exploratorio de datos"); add("Visualizar datos efectivamente"); }}, 4, d5);
				CursoPosgrado c2m3d1 = new CursoPosgrado("Machine Learning Aplicado", new ArrayList<String>() {{ add("Aplicar algoritmos de aprendizaje automático"); add("Evaluar modelos predictivos"); }}, 5, d10);
				CursoPosgrado c3m3d1 = new CursoPosgrado("Big Data y Procesamiento Distribuido", new ArrayList<String>() {{ add("Procesar grandes volúmenes de datos"); add("Diseñar pipelines de datos"); }}, 5, d15);
				CursoPosgrado c4m3d1 = new CursoPosgrado("Visualización de Datos", new ArrayList<String>() {{ add("Visualizar datos complejos"); add("Comunicar hallazgos efectivamente"); }}, 4, d20);
				CursoPosgrado c5m3d1 = new CursoPosgrado("Gestión de Proyectos de Datos", new ArrayList<String>() {{ add("Gestionar proyectos de ciencia de datos"); add("Aplicar ética en el manejo de datos"); }}, 3, d4);

				m3d1.agregarCursoPosgrado(c1m3d1);
				m3d1.agregarCursoPosgrado(c2m3d1);
				m3d1.agregarCursoPosgrado(c3m3d1);
				m3d1.agregarCursoPosgrado(c4m3d1);
				m3d1.agregarCursoPosgrado(c5m3d1);

				//Cursos de la maestria 1 del departamento 2
				CursoPosgrado c1m1d2 = new CursoPosgrado("Análisis de Sistemas de Potencia", new ArrayList<String>() {{ add("Analizar flujos de carga en sistemas eléctricos"); add("Evaluar estabilidad en sistemas de potencia");}}, 4, d21);
				CursoPosgrado c2m1d2 = new CursoPosgrado("Protecciones Eléctricas", new ArrayList<String>() {{ add("Diseñar esquemas de protección para sistemas eléctricos"); add("Analizar fallas en sistemas de potencia"); }}, 5, d26);
				CursoPosgrado c3m1d2 = new CursoPosgrado("Generación Distribuida", new ArrayList<String>() {{ add("Evaluar impactos de generación distribuida"); add("Diseñar sistemas con fuentes renovables"); }}, 4, d31);

				m1d2.agregarCursoPosgrado(c1m1d2);
				m1d2.agregarCursoPosgrado(c2m1d2);
				m1d2.agregarCursoPosgrado(c3m1d2);

				//Cursos de la maestria 2 del departamento 2
				CursoPosgrado c1m2d2 = new CursoPosgrado("Control de Procesos Industriales", new ArrayList<String>() {{ add("Diseñar sistemas de control para procesos industriales"); add("Implementar estrategias de control PID"); }}, 4, d23);
				CursoPosgrado c2m2d2 = new CursoPosgrado("Sistemas SCADA", new ArrayList<String>() {{ add("Configurar sistemas SCADA industriales"); add("Implementar monitoreo remoto de procesos"); }}, 5, d28);
				CursoPosgrado c3m2d2 = new CursoPosgrado("Robótica Industrial", new ArrayList<String>() {{ add("Programar robots industriales"); add("Diseñar células de trabajo automatizadas"); }}, 4, d33);

				m2d2.agregarCursoPosgrado(c1m2d2);
				m2d2.agregarCursoPosgrado(c2m2d2);
				m2d2.agregarCursoPosgrado(c3m2d2);

				//Cursos de la maestria 3 del departamento 2
				CursoPosgrado c1m3d2 = new CursoPosgrado("Redes de Telecomunicaciones", new ArrayList<String>() {{ add("Diseñar arquitecturas de redes de telecomunicaciones"); add("Analizar protocolos de comunicación"); }}, 4, d25);
				CursoPosgrado c2m3d2 = new CursoPosgrado("Comunicaciones Digitales", new ArrayList<String>() {{ add("Implementar sistemas de modulación digital"); add("Analizar desempeño de sistemas de comunicación"); }}, 5, d30);
				CursoPosgrado c3m3d2 = new CursoPosgrado("Redes 5G", new ArrayList<String>() {{ add("Evaluar tecnologías para redes 5G"); add("Diseñar redes de nueva generación"); }}, 4, d35);
				CursoPosgrado c4m3d2 = new CursoPosgrado("Fibra Óptica", new ArrayList<String>() {{ add("Diseñar sistemas de transmisión por fibra óptica"); add("Analizar parámetros de desempeño en fibras"); }}, 4, d40);

				m3d2.agregarCursoPosgrado(c1m3d2);
				m3d2.agregarCursoPosgrado(c2m3d2);
				m3d2.agregarCursoPosgrado(c3m3d2);
				m3d2.agregarCursoPosgrado(c4m3d2);

				//Cursos de la maestria 4 del departamento 2
				CursoPosgrado c1m4d2 = new CursoPosgrado("Convertidores Electrónicos", new ArrayList<String>() {{add("Diseñar convertidores CC-CC y CC-CA"); add("Analizar topologías de conversión"); }}, 4, d22);
				CursoPosgrado c2m4d2 = new CursoPosgrado("Accionamientos Eléctricos", new ArrayList<String>() {{add("Implementar control de motores eléctricos"); add("Diseñar sistemas de accionamiento variable"); }}, 5, d27);
				CursoPosgrado c3m4d2 = new CursoPosgrado("Calidad de Energía", new ArrayList<String>() {{add("Analizar problemas de calidad de energía"); add("Diseñar sistemas de compensación");}}, 4, d32);

				m4d2.agregarCursoPosgrado(c1m4d2);
				m4d2.agregarCursoPosgrado(c2m4d2);
				m4d2.agregarCursoPosgrado(c3m4d2);
				
				// Cursos de la maestria 1 del departamento 3
				CursoPosgrado c1m1d3 = new CursoPosgrado("Modelos Matemáticos Avanzados", new ArrayList<String>() {{ add("Aplicar modelos matemáticos a problemas complejos"); add("Desarrollar soluciones basadas en modelación matemática");  }}, 4, d41);
				CursoPosgrado c2m1d3 = new CursoPosgrado("Ecuaciones Diferenciales", new ArrayList<String>() {{ add("Resolver ecuaciones diferenciales complejas"); add("Aplicar ecuaciones diferenciales en modelado físico"); }}, 5, d46);
				CursoPosgrado c3m1d3 = new CursoPosgrado("Análisis Numérico", new ArrayList<String>() {{ add("Implementar métodos numéricos para resolver problemas matemáticos");add("Analizar errores en cálculos numéricos");}}, 4, d51);

				m1d3.agregarCursoPosgrado(c1m1d3);
				m1d3.agregarCursoPosgrado(c2m1d3);
				m1d3.agregarCursoPosgrado(c3m1d3);

				// Cursos de la maestria 2 del departamento 3
				CursoPosgrado c1m2d3 = new CursoPosgrado("Estadística Multivariante", new ArrayList<String>() {{ add("Aplicar técnicas estadísticas multivariantes"); add("Interpretar resultados de análisis multivariados"); }}, 4, d42);
				CursoPosgrado c2m2d3 = new CursoPosgrado("Diseño de Experimentos", new ArrayList<String>() {{ add("Planificar diseños experimentales eficientes");add("Analizar datos de experimentos científicos"); }}, 5, d47);
			    CursoPosgrado c3m2d3 = new CursoPosgrado("Series Temporales", new ArrayList<String>() {{add("Modelar y predecir series temporales");add("Aplicar técnicas de suavizado y descomposición"); }}, 4, d52);

				m2d3.agregarCursoPosgrado(c1m2d3);
				m2d3.agregarCursoPosgrado(c2m2d3);
				m2d3.agregarCursoPosgrado(c3m2d3);

				// Cursos de la maestria 3 del departamento 3
				CursoPosgrado c1m3d3 = new CursoPosgrado("Optimización Lineal", new ArrayList<String>() {{ add("Formular problemas de optimización lineal"); add("Resolver modelos usando métodos simplex"); }}, 4, d43);			    
				CursoPosgrado c2m3d3 = new CursoPosgrado("Programación Dinámica", new ArrayList<String>() {{ add("Aplicar principios de programación dinámica");add("Resolver problemas de optimización multietapa"); }}, 5, d48);   
				CursoPosgrado c3m3d3 = new CursoPosgrado("Teoría de Juegos", new ArrayList<String>() {{add("Analizar estrategias en situaciones competitivas"); add("Aplicar modelos de teoría de juegos");}}, 4, d53);    
				CursoPosgrado c4m3d3 = new CursoPosgrado("Optimización en Redes", new ArrayList<String>() {{add("Resolver problemas de flujo en redes"); add("Aplicar algoritmos de optimización en grafos");}}, 4, d58);

				m3d3.agregarCursoPosgrado(c1m3d3);
				m3d3.agregarCursoPosgrado(c2m3d3);
				m3d3.agregarCursoPosgrado(c3m3d3);
				m3d3.agregarCursoPosgrado(c4m3d3);

				// Cursos de la maestria 4 del departamento 3
				CursoPosgrado c1m4d3 = new CursoPosgrado("Modelos Financieros Avanzados", new ArrayList<String>() {{add("Desarrollar modelos matemáticos para finanzas");add("Evaluar riesgos en instrumentos financieros"); }}, 4, d45);		    
				CursoPosgrado c2m4d3 = new CursoPosgrado("Derivados Financieros", new ArrayList<String>() {{add("Valorar instrumentos derivados"); add("Aplicar modelos de fijación de precios"); }}, 5, d50);
				CursoPosgrado c3m4d3 = new CursoPosgrado("Gestión de Riesgos", new ArrayList<String>() {{add("Cuantificar riesgos financieros");add("Implementar estrategias de cobertura"); }}, 4, d55);

				m4d3.agregarCursoPosgrado(c1m4d3);
				m4d3.agregarCursoPosgrado(c2m4d3);
				m4d3.agregarCursoPosgrado(c3m4d3);

				// Cursos de la maestria 5 del departamento 3
				CursoPosgrado c1m5d3 = new CursoPosgrado("Algoritmos Criptográficos", new ArrayList<String>() {{ add("Implementar algoritmos criptográficos modernos");add("Analizar fortalezas de sistemas criptográficos");}}, 4, d44);	    
				CursoPosgrado c2m5d3 = new CursoPosgrado("Seguridad Computacional",  new ArrayList<String>() {{ add("Evaluar vulnerabilidades en sistemas informáticos"); add("Diseñar protocolos seguros"); }}, 5, d49);
				CursoPosgrado c3m5d3 = new CursoPosgrado("Teoría de Números Aplicada", new ArrayList<String>() {{add("Aplicar conceptos avanzados de teoría de números");add("Resolver problemas criptográficos con métodos numéricos");}}, 4, d54);
				CursoPosgrado c4m5d3 = new CursoPosgrado("Firma Digital y Autenticación", new ArrayList<String>() {{add("Implementar sistemas de firma digital"); add("Diseñar protocolos de autenticación segura"); }}, 4, d59);

				m5d3.agregarCursoPosgrado(c1m5d3);
				m5d3.agregarCursoPosgrado(c2m5d3);
				m5d3.agregarCursoPosgrado(c3m5d3);
				m5d3.agregarCursoPosgrado(c4m5d3);
			}
		});
	}
}
